services:
  # OpenAPI 服务
  openapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: openapi-service
    container_name: openapi-service
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8002:8001"
    env_file:
      - .env
    networks:
      - letever-flask-program_app_network

# 连接到已有的 juntuo.cc 项目的网络
networks:
  letever-flask-program_app_network:
    external: true
